FROM python:3.9-slim
WORKDIR /app
RUN pip3 install flask redis yfinance
EXPOSE 6380
COPY ./cache.py .
CMD ["python3", "./cache.py"]

# docker build -f Dockerfile-redis-cache -t waffle4everyone/redis-cache .