version: '3.8'

services:
  postgres:
    container_name: overmind-postgres
    image: postgres
    env_file:
    - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - 5432
    ports:
      - 5433:5432
    restart: unless-stopped

volumes:
  postgres: