version: '3.8'

services:
  postgres:
    container_name: overmind-postgres
    image: postgres
    env_file:
    - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - 5432
    ports:
      - 5433:5432
    restart: unless-stopped

  redis-master:
    container_name: redis-master
    image: redislabs/rejson
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: unless-stopped

  py-cache:
    image: py-cache
    container_name: py-cache
    build:
      context: ./cache
    depends_on:
      - redis-master
    expose:
      - 6380
    ports:
      - 6380:6380 
    restart: unless-stopped

  lstm:
    # image: tensorflow/tensorflow
    # image: tensorflow/tensorflow:1.14.0-gpu-py3
    # image: armswdev/tensorflow-arm-neoverse
    # image: tensorflow_arm64:v1.0
    container_name: lstm
    build:
      context: ./lstm
    depends_on:
      - redis-master
      - py-cache


volumes:
  postgres: