version: '3.8'

services:
  core:
    container_name: core-service
    image: core-service
    build:
      context: .
      dockerfile: core-service.dockerfile
    env_file:
      - ./trading-platform-core/.env
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - core-postgres-server
    expose:
      - ${CORE_SERVICE_PORT}
    restart: always

  auth:
    container_name: auth-service
    image: auth-service
    build:
      context: .
      dockerfile: auth-service.dockerfile
    env_file:
      - ./trading-platform-auth/.env
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - user-postgres-server
    expose:
      - ${AUTH_SERVICE_PORT}
    restart: always

  core-postgres-server:
    container_name: core-postgres-server
    image: postgres
    env_file:
    - ./trading-platform-core/.env
    environment:
      POSTGRES_DB: ${CORE_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${CORE_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CORE_SERVICE_POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - core_postgres:/data/postgres
    expose:
      - 5432
    restart: unless-stopped

  user-postgres-server:
    container_name: user-postgres-server
    image: postgres
    env_file:
    - ./trading-platform-auth/.env
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - user_postgres:/data/postgres
    expose:
      - 5432
    restart: unless-stopped

volumes:
  core_postgres:
  user_postgres:
