FROM python:3.9-slim
WORKDIR /app
COPY ./discovery.py .
RUN pip3 install flask requests
EXPOSE 6666
CMD ["python3", "./discovery.py"]

# docker build -f Dockerfile-discovery -t waffle4everyone/discovery .