global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "core"
    static_configs:
      - targets: ["core01:5001"]
  - job_name: 'Flask-Gateway'
    dns_sd_configs:
      - names: ['gateway']
        port: 5555
        type: A
        refresh_interval: 5s